package: yform_spam_protection
version: '1.0.3'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/yform_spam_protection

requires:
    redaxo: ^5.8.1
    yform: '>=3,<4'
    php:
        version: ^7.0

page:
    hidden: true

pages:
    yform/spam_protection:
        title: 'Spamschutz'

default_config:
    timer: 5
